# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http:#www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

#
# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cdi-operator
    operator.cdi.kubevirt.io: ""
    prometheus.cdi.kubevirt.io: "true"
  name: cdi-operator
  namespace: cdi
spec:
  replicas: 1
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ""
  strategy: {}
  template:
    metadata:
      labels:
        name: cdi-operator
        operator.cdi.kubevirt.io: ""
        prometheus.cdi.kubevirt.io: "true"
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: "true"
        - name: OPERATOR_VERSION
          value: v1.54.0
        - name: CONTROLLER_IMAGE
          value: {{ .Values.cdiControlerImage }} #quay.io/kubevirt/cdi-controller:v1.54.0
        - name: IMPORTER_IMAGE
          value: {{ .Values.cdiImporterImage }} #quay.io/kubevirt/cdi-importer:v1.54.0
        - name: CLONER_IMAGE
          value: {{ .Values.cdiClonerImage }}  #quay.io/kubevirt/cdi-cloner:v1.54.0
        - name: APISERVER_IMAGE
          value: {{ .Values.cdiApiServerImage }} #quay.io/kubevirt/cdi-apiserver:v1.54.0
        - name: UPLOAD_SERVER_IMAGE
          value: {{ .Values.cdiUploadServerImage }}  # quay.io/kubevirt/cdi-uploadserver:v1.54.0
        - name: UPLOAD_PROXY_IMAGE
          value: {{ .Values.cdiUploadProxyImage }}  #quay.io/kubevirt/cdi-uploadproxy:v1.54.0
        - name: VERBOSITY
          value: "1"
        - name: PULL_POLICY
          value: IfNotPresent
        - name: MONITORING_NAMESPACE
        image: {{ .Values.cdiOperatorImage }}
        imagePullPolicy: IfNotPresent
        name: cdi-operator
        ports:
        - containerPort: {{ .Values.containerPorts.cdiMetricsPort }}
          name: metrics
          protocol: TCP
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
{{- with .Values.tolerations }}
      tolerations:
{{ toYaml . | indent 6 }}
{{- end }}
{{- if .Values.nodeSelector }}
      nodeSelector:
{{ .Values.nodeSelector | toYaml | trim | indent 8 }}
{{- end }}
