# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    name: cdi-operator
    operator.cdi.kubevirt.io: ''
    prometheus.cdi.kubevirt.io: 'true'
  name: cdi-operator
  namespace: cdi
spec:
  replicas: {{ .Values.cdi.replicas }}
  selector:
    matchLabels:
      name: cdi-operator
      operator.cdi.kubevirt.io: ''
  strategy: {}
  template:
    metadata:
      labels:
        name: cdi-operator
        operator.cdi.kubevirt.io: ''
        prometheus.cdi.kubevirt.io: 'true'
    spec:
      containers:
      - env:
        - name: DEPLOY_CLUSTER_RESOURCES
          value: 'true'
        - name: OPERATOR_VERSION
          value: v1.58.0
        - name: CONTROLLER_IMAGE
          value: {{ .Values.cdi.images.tags.cdiControlerImage }}
        - name: IMPORTER_IMAGE
          value: {{ .Values.cdi.images.tags.cdiImporterImage }}
        - name: CLONER_IMAGE
          value: {{ .Values.cdi.images.tags.cdiClonerImage }}
        - name: APISERVER_IMAGE
          value: {{ .Values.cdi.images.tags.cdiApiServerImage }}
        - name: UPLOAD_SERVER_IMAGE
          value: {{ .Values.cdi.images.tags.cdiUploadServerImage }}
        - name: UPLOAD_PROXY_IMAGE
          value: {{ .Values.cdi.images.tags.cdiUploadProxyImage }}
        - name: VERBOSITY
          value: '1'
        - name: PULL_POLICY
          value: IfNotPresent
        - name: MONITORING_NAMESPACE
        image: {{ .Values.cdi.images.tags.cdiOperatorImage }}
        imagePullPolicy: IfNotPresent
        name: cdi-operator
        ports:
        - containerPort: {{ .Values.cdi.containerPorts.metricsPort }}
          name: metrics
          protocol: TCP
        resources:
          requests:
            memory: {{ .Values.cdi.resources.requests.memory }}
        securityContext:
          allowPrivilegeEscalation: false
          capabilities:
            drop:
            - ALL
          runAsNonRoot: true
          seccompProfile:
            type: RuntimeDefault
      imagePullSecrets:
      - name: {{ .Values.cdi.imagePullSecrets }}
      nodeSelector:
        kubernetes.io/os: linux
        node-role.kubernetes.io/control-plane: ''
      securityContext:
        runAsNonRoot: true
      serviceAccountName: cdi-operator
      tolerations:
      - key: CriticalAddonsOnly
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/control-plane
        operator: Exists
      - effect: NoSchedule
        key: node-role.kubernetes.io/master
        operator: Exists
