# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#

# Default values for kubevirt-app.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
---

# KubeVirt v1.1.0 configuration
kubevirt:
  replicas: 1
  componentType: "platform"
  certificateRotate:
    ca:
      duration: 720h
      renewBefore: 360h
    server:
      duration: 720h
      renewBefore: 360h
  images:
    tags:
      virtCtlImage: docker.io/starlingx/stx-kubevirt-app:stx.8.0-v1.1.0
      virtOperatorImage: quay.io/kubevirt/virt-operator:v1.1.0
      virtControllerImage: quay.io/kubevirt/virt-controller:v1.1.0
      virtLauncherImage: quay.io/kubevirt/virt-launcher:v1.1.0
      virtHandlerImage: quay.io/kubevirt/virt-handler:v1.1.0
      virtApiImage: quay.io/kubevirt/virt-api:v1.1.0
  imagePullSecrets: default-registry-key
  resources:
    requests:
      # This value for memory come from the upstream yaml
      memory: 400Mi
  containerPorts:
    metricsPort: 8443
    webhooksPort: 8444
  readinessProbePort: 8443


# CDI v.1.58.0(Containerized Data Importer) configuration
cdi:
  replicas: 1
  componentType: "platform"
  certificateRotate:
    ca:
      duration: 720h
      renewBefore: 360h
    server:
      duration: 720h
      renewBefore: 360h
  featureGates:
    - HonorWaitForFirstConsumer
  images:
    tags:
      cdiOperatorImage: quay.io/kubevirt/cdi-operator:v1.58.0
      cdiControlerImage: quay.io/kubevirt/cdi-controller:v1.58.0
      cdiImporterImage: quay.io/kubevirt/cdi-importer:v1.58.0
      cdiClonerImage: quay.io/kubevirt/cdi-cloner:v1.58.0
      cdiApiServerImage: quay.io/kubevirt/cdi-apiserver:v1.58.0
      cdiUploadServerImage: quay.io/kubevirt/cdi-uploadserver:v1.58.0
      cdiUploadProxyImage: quay.io/kubevirt/cdi-uploadproxy:v1.58.0
  imagePullSecrets: default-registry-key
  resources:
    requests:
      # The values for memory comes from the upstream yaml
      memory: 150Mi
  containerPorts:
    metricsPort: 8080
