#
## Copyright (c) 2022 Wind River Systems, Inc.
##
## SPDX-License-Identifier: Apache-2.0
#
---
apiVersion: "helm.toolkit.fluxcd.io/v2beta1"
kind: HelmRelease
metadata:
  name: kubevirt-app
  namespace: kubevirt
  labels:
    chart_group: starlingx-kubevirt-charts
spec:
  releaseName: kubevirt-app
  chart:
    spec:
      chart: kubevirt-app
      version: 0.1.0
      sourceRef:
        kind: HelmRepository
        name: stx-platform
        namespace: kube-system
  interval: 1m
  timeout: 30m
  test:
    enable: false
  install:
    disableHooks: false
  upgrade:
    disableHooks: false
  valuesFrom:
    - kind: Secret
      name: kubevirt-static-overrides
      valuesKey: kubevirt-static-overrides.yaml
    - kind: Secret
      name: kubevirt-system-overrides
      valuesKey: kubevirt-system-overrides.yaml
