# Copyright (c) 2022 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
---
namespace: kubevirt
resources:
  - helmrelease.yaml
secretGenerator:
  - name: kubevirt-system-overrides
    files:
      - kubevirt-system-overrides.yaml
  - name: kubevirt-static-overrides
    files:
      - kubevirt-static-overrides.yaml
generatorOptions:
  disableNameSuffixHash: true
