#
# Copyright (c) 2024 Wind River Systems, Inc.
#
# SPDX-License-Identifier: Apache-2.0
#
# All Rights Reserved.
#
ARG BASE
FROM ${BASE}
ADD https://github.com/kubevirt/kubevirt/releases/download/v1.1.0/virtctl-v1.1.0-linux-amd64 .
RUN chmod a+rwx ./virtctl-v1.1.0-linux-amd64
